import '../models/country/country_model.dart';

List<CountryModel> get kCountries => List<CountryModel>.from(countriesList.map((model) => CountryModel.fromJson(model)));

final countriesList = [
  {"nameEn": "Afghanistan", "nameAr": "أفغانستان", "dialCode": "+93", "code": "AF"},
  {"nameEn": "Albania", "nameAr": "ألبانيا", "dialCode": "+355", "code": "AL"},
  {"nameEn": "Algeria", "nameAr": "الجزائر", "dialCode": "+213", "code": "DZ"},
  {"nameEn": "Andorra", "nameAr": "أندورا", "dialCode": "+376", "code": "AD"},
  {"nameEn": "Angola", "nameAr": "أنغولا", "dialCode": "+244", "code": "AO"},
  {"nameEn": "Antigua and Barbuda", "nameAr": "أنتيغوا وبربودا", "dialCode": "+1 268", "code": "AG"},
  {"nameEn": "Argentina", "nameAr": "الأرجنتين", "dialCode": "+54", "code": "AR"},
  {"nameEn": "Armenia", "nameAr": "أرمينيا", "dialCode": "+374", "code": "AM"},
  {"nameEn": "Australia", "nameAr": "أستراليا", "dialCode": "+61", "code": "AU"},
  {"nameEn": "Austria", "nameAr": "النمسا", "dialCode": "+43", "code": "AT"},
  {"nameEn": "Azerbaijan", "nameAr": "أذربيجان", "dialCode": "+994", "code": "AZ"},
  {"nameEn": "Bahamas", "nameAr": "الباهاما", "dialCode": "+1 242", "code": "BS"},
  {"nameEn": "Bahrain", "nameAr": "البحرين", "dialCode": "+973", "code": "BH"},
  {"nameEn": "Bangladesh", "nameAr": "بنغلاديش", "dialCode": "+880", "code": "BD"},
  {"nameEn": "Barbados", "nameAr": "بربادوس", "dialCode": "+1 246", "code": "BB"},
  {"nameEn": "Belarus", "nameAr": "بيلاروسيا", "dialCode": "+375", "code": "BY"},
  {"nameEn": "Belgium", "nameAr": "بلجيكا", "dialCode": "+32", "code": "BE"},
  {"nameEn": "Belize", "nameAr": "بليز", "dialCode": "+501", "code": "BZ"},
  {"nameEn": "Benin", "nameAr": "بنين", "dialCode": "+229", "code": "BJ"},
  {"nameEn": "Bhutan", "nameAr": "بوتان", "dialCode": "+975", "code": "BT"},
  {"nameEn": "Bolivia", "nameAr": "بوليفيا", "dialCode": "+591", "code": "BO"},
  {"nameEn": "Bosnia and Herzegovina", "nameAr": "البوسنة والهرسك", "dialCode": "+387", "code": "BA"},
  {"nameEn": "Botswana", "nameAr": "بوتسوانا", "dialCode": "+267", "code": "BW"},
  {"nameEn": "Brazil", "nameAr": "البرازيل", "dialCode": "+55", "code": "BR"},
  {"nameEn": "Brunei", "nameAr": "بروناي", "dialCode": "+673", "code": "BN"},
  {"nameEn": "Bulgaria", "nameAr": "بلغاريا", "dialCode": "+359", "code": "BG"},
  {"nameEn": "Burkina Faso", "nameAr": "بوركينا فاسو", "dialCode": "+226", "code": "BF"},
  {"nameEn": "Burundi", "nameAr": "بوروندي", "dialCode": "+257", "code": "BI"},
  {"nameEn": "Cabo Verde", "nameAr": "الرأس الأخضر", "dialCode": "+238", "code": "CV"},
  {"nameEn": "Cambodia", "nameAr": "كمبوديا", "dialCode": "+855", "code": "KH"},
  {"nameEn": "Cameroon", "nameAr": "الكاميرون", "dialCode": "+237", "code": "CM"},
  {"nameEn": "Canada", "nameAr": "كندا", "dialCode": "+1", "code": "CA"},
  {"nameEn": "Central African Republic", "nameAr": "جمهورية أفريقيا الوسطى", "dialCode": "+236", "code": "CF"},
  {"nameEn": "Chad", "nameAr": "تشاد", "dialCode": "+235", "code": "TD"},
  {"nameEn": "Chile", "nameAr": "تشيلي", "dialCode": "+56", "code": "CL"},
  {"nameEn": "China", "nameAr": "الصين", "dialCode": "+86", "code": "CN"},
  {"nameEn": "Colombia", "nameAr": "كولومبيا", "dialCode": "+57", "code": "CO"},
  {"nameEn": "Comoros", "nameAr": "جزر القمر", "dialCode": "+269", "code": "KM"},
  {"nameEn": "Congo (Congo-Brazzaville)", "nameAr": "الكونغو (برازافيل)", "dialCode": "+242", "code": "CG"},
  {"nameEn": "Congo, Democratic Republic of the Congo (Kinshasa)", "nameAr": "جمهورية الكونغو الديمقراطية (كينشاسا)", "dialCode": "+243", "code": "CD"},
  {"nameEn": "Costa Rica", "nameAr": "كوستاريكا", "dialCode": "+506", "code": "CR"},
  {"nameEn": "Croatia", "nameAr": "كرواتيا", "dialCode": "+385", "code": "HR"},
  {"nameEn": "Cuba", "nameAr": "كوبا", "dialCode": "+53", "code": "CU"},
  {"nameEn": "Cyprus", "nameAr": "قبرص", "dialCode": "+357", "code": "CY"},
  {"nameEn": "Czech Republic", "nameAr": "جمهورية التشيك", "dialCode": "+420", "code": "CZ"},
  {"nameEn": "Denmark", "nameAr": "الدنمارك", "dialCode": "+45", "code": "DK"},
  {"nameEn": "Djibouti", "nameAr": "جيبوتي", "dialCode": "+253", "code": "DJ"},
  {"nameEn": "Dominica", "nameAr": "دومينيكا", "dialCode": "+1 767", "code": "DM"},
  {"nameEn": "Ecuador", "nameAr": "الإكوادور", "dialCode": "+593", "code": "EC"},
  {"nameEn": "Egypt", "nameAr": "مصر", "dialCode": "+20", "code": "EG"},
  {"nameEn": "El Salvador", "nameAr": "السلفادور", "dialCode": "+503", "code": "SV"},
  {"nameEn": "Equatorial Guinea", "nameAr": "غينيا الاستوائية", "dialCode": "+240", "code": "GQ"},
  {"nameEn": "Eritrea", "nameAr": "إريتريا", "dialCode": "+291", "code": "ER"},
  {"nameEn": "Estonia", "nameAr": "إستونيا", "dialCode": "+372", "code": "EE"},
  {"nameEn": "Eswatini", "nameAr": "إسواتيني", "dialCode": "+268", "code": "SZ"},
  {"nameEn": "Ethiopia", "nameAr": "إثيوبيا", "dialCode": "+251", "code": "ET"},
  {"nameEn": "Fiji", "nameAr": "فيجي", "dialCode": "+679", "code": "FJ"},
  {"nameEn": "Finland", "nameAr": "فنلندا", "dialCode": "+358", "code": "FI"},
  {"nameEn": "France", "nameAr": "فرنسا", "dialCode": "+33", "code": "FR"},
  {"nameEn": "Gabon", "nameAr": "الغابون", "dialCode": "+241", "code": "GA"},
  {"nameEn": "Gambia", "nameAr": "غامبيا", "dialCode": "+220", "code": "GM"},
  {"nameEn": "Georgia", "nameAr": "جورجيا", "dialCode": "+995", "code": "GE"},
  {"nameEn": "Germany", "nameAr": "ألمانيا", "dialCode": "+49", "code": "DE"},
  {"nameEn": "Ghana", "nameAr": "غانا", "dialCode": "+233", "code": "GH"},
  {"nameEn": "Greece", "nameAr": "اليونان", "dialCode": "+30", "code": "GR"},
  {"nameEn": "Grenada", "nameAr": "غرينادا", "dialCode": "+1 473", "code": "GD"},
  {"nameEn": "Guatemala", "nameAr": "غواتيمالا", "dialCode": "+502", "code": "GT"},
  {"nameEn": "Guinea", "nameAr": "غينيا", "dialCode": "+224", "code": "GN"},
  {"nameEn": "Guinea-Bissau", "nameAr": "غينيا بيساو", "dialCode": "+245", "code": "GW"},
  {"nameEn": "Guyana", "nameAr": "غيانا", "dialCode": "+592", "code": "GY"},
  {"nameEn": "Haiti", "nameAr": "هايتي", "dialCode": "+509", "code": "HT"},
  {"nameEn": "Honduras", "nameAr": "هندوراس", "dialCode": "+504", "code": "HN"},
  {"nameEn": "Hungary", "nameAr": "المجر", "dialCode": "+36", "code": "HU"},
  {"nameEn": "Iceland", "nameAr": "آيسلندا", "dialCode": "+354", "code": "IS"},
  {"nameEn": "India", "nameAr": "الهند", "dialCode": "+91", "code": "IN"},
  {"nameEn": "Indonesia", "nameAr": "إندونيسيا", "dialCode": "+62", "code": "ID"},
  {"nameEn": "Iran", "nameAr": "إيران", "dialCode": "+98", "code": "IR"},
  {"nameEn": "Iraq", "nameAr": "العراق", "dialCode": "+964", "code": "IQ"},
  {"nameEn": "Ireland", "nameAr": "أيرلندا", "dialCode": "+353", "code": "IE"},
  {"nameEn": "Italy", "nameAr": "إيطاليا", "dialCode": "+39", "code": "IT"},
  {"nameEn": "Jamaica", "nameAr": "جامايكا", "dialCode": "+1 876", "code": "JM"},
  {"nameEn": "Japan", "nameAr": "اليابان", "dialCode": "+81", "code": "JP"},
  {"nameEn": "Jordan", "nameAr": "الأردن", "dialCode": "+962", "code": "JO"},
  {"nameEn": "Kazakhstan", "nameAr": "كازاخستان", "dialCode": "+7", "code": "KZ"},
  {"nameEn": "Kenya", "nameAr": "كينيا", "dialCode": "+254", "code": "KE"},
  {"nameEn": "Kiribati", "nameAr": "كيريباتي", "dialCode": "+686", "code": "KI"},
  {"nameEn": "Korea, North", "nameAr": "كوريا الشمالية", "dialCode": "+850", "code": "KP"},
  {"nameEn": "Korea, South", "nameAr": "كوريا الجنوبية", "dialCode": "+82", "code": "KR"},
  {"nameEn": "Kosovo", "nameAr": "كوسوفو", "dialCode": "+383", "code": "XK"},
  {"nameEn": "Kuwait", "nameAr": "الكويت", "dialCode": "+965", "code": "KW"},
  {"nameEn": "Kyrgyzstan", "nameAr": "قيرغيزستان", "dialCode": "+996", "code": "KG"},
  {"nameEn": "Laos", "nameAr": "لاوس", "dialCode": "+856", "code": "LA"},
  {"nameEn": "Latvia", "nameAr": "لاتفيا", "dialCode": "+371", "code": "LV"},
  {"nameEn": "Lebanon", "nameAr": "لبنان", "dialCode": "+961", "code": "LB"},
  {"nameEn": "Lesotho", "nameAr": "ليسوتو", "dialCode": "+266", "code": "LS"},
  {"nameEn": "Liberia", "nameAr": "ليبيريا", "dialCode": "+231", "code": "LR"},
  {"nameEn": "Libya", "nameAr": "ليبيا", "dialCode": "+218", "code": "LY"},
  {"nameEn": "Liechtenstein", "nameAr": "ليختنشتاين", "dialCode": "+423", "code": "LI"},
  {"nameEn": "Lithuania", "nameAr": "ليتوانيا", "dialCode": "+370", "code": "LT"},
  {"nameEn": "Luxembourg", "nameAr": "لوكسمبورغ", "dialCode": "+352", "code": "LU"},
  {"nameEn": "Madagascar", "nameAr": "مدغشقر", "dialCode": "+261", "code": "MG"},
  {"nameEn": "Malawi", "nameAr": "مالاوي", "dialCode": "+265", "code": "MW"},
  {"nameEn": "Malaysia", "nameAr": "ماليزيا", "dialCode": "+60", "code": "MY"},
  {"nameEn": "Maldives", "nameAr": "جزر المالديف", "dialCode": "+960", "code": "MV"},
  {"nameEn": "Mali", "nameAr": "مالي", "dialCode": "+223", "code": "ML"},
  {"nameEn": "Malta", "nameAr": "مالطا", "dialCode": "+356", "code": "MT"},
  {"nameEn": "Marshall Islands", "nameAr": "جزر مارشال", "dialCode": "+692", "code": "MH"},
  {"nameEn": "Mauritania", "nameAr": "موريتانيا", "dialCode": "+222", "code": "MR"},
  {"nameEn": "Mauritius", "nameAr": "موريشيوس", "dialCode": "+230", "code": "MU"},
  {"nameEn": "Mexico", "nameAr": "المكسيك", "dialCode": "+52", "code": "MX"},
  {"nameEn": "Micronesia", "nameAr": "ميكرونيزيا", "dialCode": "+691", "code": "FM"},
  {"nameEn": "Moldova", "nameAr": "مولدوفا", "dialCode": "+373", "code": "MD"},
  {"nameEn": "Monaco", "nameAr": "موناكو", "dialCode": "+377", "code": "MC"},
  {"nameEn": "Mongolia", "nameAr": "منغوليا", "dialCode": "+976", "code": "MN"},
  {"nameEn": "Montenegro", "nameAr": "الجبل الأسود", "dialCode": "+382", "code": "ME"},
  {"nameEn": "Morocco", "nameAr": "المغرب", "dialCode": "+212", "code": "MA"},
  {"nameEn": "Mozambique", "nameAr": "موزمبيق", "dialCode": "+258", "code": "MZ"},
  {"nameEn": "Myanmar", "nameAr": "ميانمار", "dialCode": "+95", "code": "MM"},
  {"nameEn": "Namibia", "nameAr": "ناميبيا", "dialCode": "+264", "code": "NA"},
  {"nameEn": "Nauru", "nameAr": "ناورو", "dialCode": "+674", "code": "NR"},
  {"nameEn": "Nepal", "nameAr": "نيبال", "dialCode": "+977", "code": "NP"},
  {"nameEn": "Netherlands", "nameAr": "هولندا", "dialCode": "+31", "code": "NL"},
  {"nameEn": "New Zealand", "nameAr": "نيوزيلندا", "dialCode": "+64", "code": "NZ"},
  {"nameEn": "Nicaragua", "nameAr": "نيكاراغوا", "dialCode": "+505", "code": "NI"},
  {"nameEn": "Niger", "nameAr": "النيجر", "dialCode": "+227", "code": "NE"},
  {"nameEn": "Nigeria", "nameAr": "نيجيريا", "dialCode": "+234", "code": "NG"},
  {"nameEn": "North Macedonia", "nameAr": "مقدونيا الشمالية", "dialCode": "+389", "code": "MK"},
  {"nameEn": "Norway", "nameAr": "النرويج", "dialCode": "+47", "code": "NO"},
  {"nameEn": "Oman", "nameAr": "عُمان", "dialCode": "+968", "code": "OM"},
  {"nameEn": "Pakistan", "nameAr": "باكستان", "dialCode": "+92", "code": "PK"},
  {"nameEn": "Palau", "nameAr": "بالاو", "dialCode": "+680", "code": "PW"},
  {"nameEn": "Palestine", "nameAr": "فلسطين", "dialCode": "+970", "code": "PS"},
  {"nameEn": "Panama", "nameAr": "بنما", "dialCode": "+507", "code": "PA"},
  {"nameEn": "Papua New Guinea", "nameAr": "بابوا غينيا الجديدة", "dialCode": "+675", "code": "PG"},
  {"nameEn": "Paraguay", "nameAr": "باراغواي", "dialCode": "+595", "code": "PY"},
  {"nameEn": "Peru", "nameAr": "بيرو", "dialCode": "+51", "code": "PE"},
  {"nameEn": "Philippines", "nameAr": "الفلبين", "dialCode": "+63", "code": "PH"},
  {"nameEn": "Poland", "nameAr": "بولندا", "dialCode": "+48", "code": "PL"},
  {"nameEn": "Portugal", "nameAr": "البرتغال", "dialCode": "+351", "code": "PT"},
  {"nameEn": "Qatar", "nameAr": "قطر", "dialCode": "+974", "code": "QA"},
  {"nameEn": "Romania", "nameAr": "رومانيا", "dialCode": "+40", "code": "RO"},
  {"nameEn": "Russia", "nameAr": "روسيا", "dialCode": "+7", "code": "RU"},
  {"nameEn": "Rwanda", "nameAr": "رواندا", "dialCode": "+250", "code": "RW"},
  {"nameEn": "Saint Kitts and Nevis", "nameAr": "سانت كيتس ونيفيس", "dialCode": "+1 869", "code": "KN"},
  {"nameEn": "Saint Lucia", "nameAr": "سانت لوسيا", "dialCode": "+1 758", "code": "LC"},
  {"nameEn": "Saint Vincent and the Grenadines", "nameAr": "سانت فنسنت وجزر غرينادين", "dialCode": "+1 784", "code": "VC"},
  {"nameEn": "Samoa", "nameAr": "ساموا", "dialCode": "+685", "code": "WS"},
  {"nameEn": "San Marino", "nameAr": "سان مارينو", "dialCode": "+378", "code": "SM"},
  {"nameEn": "Sao Tome and Principe", "nameAr": "ساو تومي وبرينسيبي", "dialCode": "+239", "code": "ST"},
  {"nameEn": "Saudi Arabia", "nameAr": "المملكة العربية السعودية", "dialCode": "+966", "code": "SA"},
  {"nameEn": "Senegal", "nameAr": "السنغال", "dialCode": "+221", "code": "SN"},
  {"nameEn": "Serbia", "nameAr": "صربيا", "dialCode": "+381", "code": "RS"},
  {"nameEn": "Seychelles", "nameAr": "سيشل", "dialCode": "+248", "code": "SC"},
  {"nameEn": "Sierra Leone", "nameAr": "سيراليون", "dialCode": "+232", "code": "SL"},
  {"nameEn": "Singapore", "nameAr": "سنغافورة", "dialCode": "+65", "code": "SG"},
  {"nameEn": "Slovakia", "nameAr": "سلوفاكيا", "dialCode": "+421", "code": "SK"},
  {"nameEn": "Slovenia", "nameAr": "سلوفينيا", "dialCode": "+386", "code": "SI"},
  {"nameEn": "Solomon Islands", "nameAr": "جزر سليمان", "dialCode": "+677", "code": "SB"},
  {"nameEn": "Somalia", "nameAr": "الصومال", "dialCode": "+252", "code": "SO"},
  {"nameEn": "South Africa", "nameAr": "جنوب أفريقيا", "dialCode": "+27", "code": "ZA"},
  {"nameEn": "South Sudan", "nameAr": "جنوب السودان", "dialCode": "+211", "code": "SS"},
  {"nameEn": "Spain", "nameAr": "إسبانيا", "dialCode": "+34", "code": "ES"},
  {"nameEn": "Sri Lanka", "nameAr": "سريلانكا", "dialCode": "+94", "code": "LK"},
  {"nameEn": "Sudan", "nameAr": "السودان", "dialCode": "+249", "code": "SD"},
  {"nameEn": "Suriname", "nameAr": "سورينام", "dialCode": "+597", "code": "SR"},
  {"nameEn": "Sweden", "nameAr": "السويد", "dialCode": "+46", "code": "SE"},
  {"nameEn": "Switzerland", "nameAr": "سويسرا", "dialCode": "+41", "code": "CH"},
  {"nameEn": "Syria", "nameAr": "سوريا", "dialCode": "+963", "code": "SY"},
  {"nameEn": "Taiwan", "nameAr": "تايوان", "dialCode": "+886", "code": "TW"},
  {"nameEn": "Tajikistan", "nameAr": "طاجيكستان", "dialCode": "+992", "code": "TJ"},
  {"nameEn": "Tanzania", "nameAr": "تانزانيا", "dialCode": "+255", "code": "TZ"},
  {"nameEn": "Thailand", "nameAr": "تايلاند", "dialCode": "+66", "code": "TH"},
  {"nameEn": "Timor-Leste", "nameAr": "تيمور الشرقية", "dialCode": "+670", "code": "TL"},
  {"nameEn": "Togo", "nameAr": "توغو", "dialCode": "+228", "code": "TG"},
  {"nameEn": "Tonga", "nameAr": "تونغا", "dialCode": "+676", "code": "TO"},
  {"nameEn": "Trinidad and Tobago", "nameAr": "ترينيداد وتوباغو", "dialCode": "+1 868", "code": "TT"},
  {"nameEn": "Tunisia", "nameAr": "تونس", "dialCode": "+216", "code": "TN"},
  {"nameEn": "Turkey", "nameAr": "تركيا", "dialCode": "+90", "code": "TR"},
  {"nameEn": "Turkmenistan", "nameAr": "تركمانستان", "dialCode": "+993", "code": "TM"},
  {"nameEn": "Tuvalu", "nameAr": "توفالو", "dialCode": "+688", "code": "TV"},
  {"nameEn": "Uganda", "nameAr": "أوغندا", "dialCode": "+256", "code": "UG"},
  {"nameEn": "Ukraine", "nameAr": "أوكرانيا", "dialCode": "+380", "code": "UA"},
  {"nameEn": "United Arab Emirates", "nameAr": "الإمارات العربية المتحدة", "dialCode": "+971", "code": "AE"},
  {"nameEn": "United Kingdom", "nameAr": "المملكة المتحدة", "dialCode": "+44", "code": "GB"},
  {"nameEn": "United States", "nameAr": "الولايات المتحدة", "dialCode": "+1", "code": "US"},
  {"nameEn": "Uruguay", "nameAr": "أوروغواي", "dialCode": "+598", "code": "UY"},
  {"nameEn": "Uzbekistan", "nameAr": "أوزبكستان", "dialCode": "+998", "code": "UZ"},
  {"nameEn": "Vanuatu", "nameAr": "فانواتو", "dialCode": "+678", "code": "VU"},
  {"nameEn": "Vatican City", "nameAr": "الفاتيكان", "dialCode": "+39", "code": "VA"},
  {"nameEn": "Venezuela", "nameAr": "فنزويلا", "dialCode": "+58", "code": "VE"},
  {"nameEn": "Vietnam", "nameAr": "فيتنام", "dialCode": "+84", "code": "VN"},
  {"nameEn": "Yemen", "nameAr": "اليمن", "dialCode": "+967", "code": "YE"},
  {"nameEn": "Zambia", "nameAr": "زامبيا", "dialCode": "+260", "code": "ZM"},
  {"nameEn": "Zimbabwe", "nameAr": "زيمبابوي", "dialCode": "+263", "code": "ZW"}
];
